int STRING_RUNTIME_ERROR;
typedef struct String{
    char * data;
    long len;
}String;
void SET_STRING_ERROR(int error);
void WriteLine(String *str);
void Write(String *str);
String* FreeString(String *str);
String*  FreeStringData(String *str);
int IsEqualChars(String *a,char *b);
int IsEqual(String *a,String *b);
String * NewString(int len);
String * IncreaseStringSize(String *str,int len);
String * InitString(char *src);
String * AppendStringChar(String * des,char src);
String * AppendStringChars(String * des,char *src);
String * AppendString(String * des,String *src);
String *SetString_(String *des,char *src);
String *SetString(String *des,String *src);
String * InsertString_(String *des,int index,char *src);
String * InsertString(String *des,int index,String *src);
String *SubStr(String *str,int start,int end,int step);
int StringContains(String *str,String *content);
String *UpperCase(String *str);
String *LowerCase(String *str);
int IsWhiteSpace(char c);
String *ReadLine();
void PressEnter(char *text);
int EmptyString(String * str);
int IsStringNumber(String *str);
int StringToInt(String *str);
double StringToDouble(String *str);
float StringToFloat(String *str);
String * IntToString(int num);
String * DoubleToString(double num);
String * FloatToString(float num);
